# Feature Engineering

## Scaling Features

Scaling features is important to ensure that all features contribute equally to the model. Common scaling techniques include standardization (z-score normalization) and min-max scaling. Standardization transforms features to have a mean of 0 and a standard deviation of 1, while min-max scaling rescales features to a fixed range, typically [0, 1].

```python title="example1.py"
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Sample data
data = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])

# Standardization
standard_scaler = StandardScaler()
data_standardized = standard_scaler.fit_transform(data)
print('Standardized data:', data_standardized)

# Min-Max Scaling
min_max_scaler = MinMaxScaler()
data_minmax = min_max_scaler.fit_transform(data)
print('Min-Max scaled data:', data_minmax)
```

> **Try it in Google Colab:** [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/shastrula/ailearningclub-courses/blob/main/scikit-learn-machine-learning/mod-14.ipynb)


```
Standardized data: [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
Min-Max scaled data: [[0.   0. ]
 [0.25  0.25 ]
 [0.5   0.5  ]
 [0.75  0.75 ]
 [1.    1.  ]]
```

## Encoding Categorical Features

Categorical features need to be encoded into numerical values for machine learning models to process them. Common encoding techniques include one-hot encoding and ordinal encoding. One-hot encoding creates binary columns for each category, while ordinal encoding assigns a unique integer to each category based on some order.

```python title="example2.py"
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

# Sample data
categories = np.array([['cat'], ['dog'], ['cat'], ['bird']])

# One-Hot Encoding
one_hot_encoder = OneHotEncoder()
data_onehot = one_hot_encoder.fit_transform(categories).toarray()
print('One-Hot encoded data:', data_onehot)

# Ordinal Encoding
ordinal_encoder = OrdinalEncoder()
data_ordinal = ordinal_encoder.fit_transform(categories)
print('Ordinal encoded data:', data_ordinal)
```

```
One-Hot encoded data: [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Ordinal encoded data: [[1.]
 [2.]
 [1.]
 [0.]]
```

> **💡 Tip:** Avoid multicollinearity when using one-hot encoding by dropping one category to prevent redundant information.

<div class="quiz" data-correct="1">
  <p class="font-semibold mb-3">❓ Which scaling technique transforms features to have a mean of 0 and a standard deviation of 1?</p>
  <div class="space-y-2">
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387056000" value="0">
      <span>Min-Max Scaling</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387056000" value="1">
      <span>Standardization</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387056000" value="2">
      <span>Normalization</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387056000" value="3">
      <span>Robust Scaling</span>
    </label>
  </div>
  <button class="quiz-btn mt-3 px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700">Check Answer</button>
  <p class="quiz-result text-sm mt-2 hidden"></p>
</div>

<div class="quiz" data-correct="2">
  <p class="font-semibold mb-3">❓ Which encoding technique creates binary columns for each category?</p>
  <div class="space-y-2">
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387046848" value="0">
      <span>Ordinal Encoding</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387046848" value="1">
      <span>Label Encoding</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387046848" value="2">
      <span>One-Hot Encoding</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4387046848" value="3">
      <span>Binary Encoding</span>
    </label>
  </div>
  <button class="quiz-btn mt-3 px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700">Check Answer</button>
  <p class="quiz-result text-sm mt-2 hidden"></p>
</div>

## Key Concepts

## Check Your Understanding