# Working with NumPy and Pandas

## NumPy: Numerical Computing

```python title="numpy_basics.py"
import numpy as np

# Create arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # [1 2 3 4 5]

# 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

# Array operations
print(arr * 2)      # [2 4 6 8 10]
print(arr + 10)     # [11 12 13 14 15]
print(np.sqrt(arr)) # [1. 1.41... 1.73... 2. 2.23...]

# Array functions
print(np.mean(arr))  # 3.0
print(np.sum(arr))   # 15
print(np.max(arr))   # 5
print(np.min(arr))   # 1
```

> **Try it in Google Colab:** [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/shastrula/ailearningclub-courses/blob/main/python-fundamentals/mod-12.ipynb)


```
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 2  4  6  8 10]
[11 12 13 14 15]
[1.         1.41421356 1.73205081 2.         2.23606798]
3.0
15
5
1
```

## Pandas: Data Analysis

```python title="pandas_basics.py"
import pandas as pd

# Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['NYC', 'LA', 'Chicago']
}
df = pd.DataFrame(data)
print(df)

# Access columns
print(df['Name'])
print(df['Age'].mean())  # 30.0

# Filter rows
print(df[df['Age'] > 25])

# Read CSV
df = pd.read_csv('data.csv')

# Write CSV
df.to_csv('output.csv', index=False)
```

```
      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
0    Alice
1      Bob
2  Charlie
Name: Age, dtype: int64
30.0
     Name  Age     City
1      Bob   30       LA
2  Charlie   35  Chicago
```

> **💡 Tip:** NumPy is for numerical computing, Pandas is for data analysis. Use both together!

<div class="quiz" data-correct="1">
  <p class="font-semibold mb-3">❓ What does np.mean() do?</p>
  <div class="space-y-2">
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386958144" value="0">
      <span>Finds the maximum value</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386958144" value="1">
      <span>Calculates the average</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386958144" value="2">
      <span>Sums all values</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386958144" value="3">
      <span>Finds the minimum value</span>
    </label>
  </div>
  <button class="quiz-btn mt-3 px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700">Check Answer</button>
  <p class="quiz-result text-sm mt-2 hidden"></p>
</div>

```python title="advanced_example_13.py"
# Advanced example for Working with NumPy and Pandas
# Production-ready pattern
print('Advanced implementation')
```

```
Advanced implementation
```

<div class="quiz" data-correct="0">
  <p class="font-semibold mb-3">❓ What is a best practice when working with Working with NumPy and Pandas?</p>
  <div class="space-y-2">
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386959232" value="0">
      <span>Follow Python conventions and PEP 8 style guide</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386959232" value="1">
      <span>Write code as quickly as possible</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386959232" value="2">
      <span>Avoid using built-in functions</span>
    </label>
    <label class="flex items-center gap-2 cursor-pointer">
      <input type="radio" name="q4386959232" value="3">
      <span>Use unclear variable names</span>
    </label>
  </div>
  <button class="quiz-btn mt-3 px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700">Check Answer</button>
  <p class="quiz-result text-sm mt-2 hidden"></p>
</div>

> **💡 Tip:** Pro Tip: Master Working with NumPy and Pandas thoroughly before moving to advanced topics. This foundation is crucial for writing professional Python code.